### ISSUE TITLE
Guild Announcement of CEDT 02 Guild Building Day

### ISSUE THREAD

**Issue by understann** [CEDT-Chula/cedt-community#17]
### To-Do
- [ ] UI Design
- [ ] Frontend Development
- [ ] Finding and Show Guild System

### Expected Result

- [ ] The Design align with the Social Media campaign visual
- [ ] The Frontend Align with the designed UI
- [ ] User can input their Name in Text Box (or anything)
- [ ] User can get their guild detail based on their input
