### ISSUE TITLE
[Dev] Guild Announcement For CEDT 02

### ISSUE THREAD

**Issue by understann** [CEDT-Chula/cedt-community#19]
### To-Do
- [x] UI Design
- [ ] Frontend Development
- [ ] Finding and Show Guild System

### Expected Result

- [x] The Design align with the Social Media campaign visual
- [ ] The Frontend Align with the designed UI
- [ ] User can input their Name in Text Box (or anything)
- [ ] User can get their guild detail based on their input
